### ISSUE TITLE
Context?

### ISSUE THREAD

**Issue by ManuelMines** [ArchGryphon9362/exo-the-game#1]
So you are a white shadowless (unless you go to a side) cube on a red/pink/faded plain and the camera doesn't move and you fall of the  edge and game quits XD
![image](https://user-images.githubusercontent.com/55859604/65730586-3210a000-e0ba-11e9-8af5-006ac4e35c77.png)

**Comment by ArchGryphon9362** [comment]
Yes but this is only to fine tune the controls and only then i'm making the proper game
